---
- name: Log in (obtain access token)
  community.okd.openshift_auth:
    host: "{{ sap_vm_provision_ocp_endpoint }}"
    username: "{{ sap_vm_provision_ocp_admin_username }}"
    password: "{{ sap_vm_provision_ocp_admin_password }}"
    ca_cert: "{{ sap_vm_provision_ocp_ca_cert }}"
  register: __sap_vm_provision_register_ocp_auth_results

- name: Provision hosts to OpenShift
  register: register_provisioned_hosts
  ansible.builtin.include_tasks:
    file: "{{ 'platform_' + sap_vm_provision_iac_type }}/{{ sap_vm_provision_iac_platform }}/execute_provision.yml"
