---
- name: Ansible Play to run sap_hypervisor_node_preconfigure Ansible Role
  hosts: all
  gather_facts: true
  serial: 1
  vars:
    sap_hypervisor_node_platform: redhat_ocp_virt
  tasks:
    - name: Log into Red Hat OpenShift cluster (obtain access token)
      community.okd.openshift_auth:
        host: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
        username: "{{ sap_hypervisor_node_preconfigure_ocp_admin_username }}"
        password: "{{ sap_hypervisor_node_preconfigure_ocp_admin_password }}"
        ca_cert: "{{ sap_hypervisor_node_preconfigure_ocp_ca_cert }}"
      register: __sap_vm_provision_register_ocp_auth_results

    - name: Invoke role with credentials set as environment variables
      delegate_to: "{{ inventory_hostname }}"
      delegate_facts: true
      environment:
        KUBECONFIG: "{{ sap_hypervisor_node_preconfigure_ocp_kubeconfig_path }}"
        K8S_AUTH_HOST: "{{ sap_hypervisor_node_preconfigure_ocp_endpoint }}"
        K8S_AUTH_API_KEY: "{{ __sap_vm_provision_register_ocp_auth_results.openshift_auth.api_key }}"
        K8S_AUTH_SSL_CA_CERT: "{{ sap_hypervisor_node_preconfigure_ocp_ca_cert }}"
        K8S_AUTH_USERNAME: "{{ sap_hypervisor_node_preconfigure_ocp_admin_username }}"
        K8S_AUTH_PASSWORD: "{{ sap_hypervisor_node_preconfigure_ocp_admin_password }}"
      block:
        - name: Include sap_hypervisor_node_preconfigure Ansible Role
          ansible.builtin.include_role:
            name: community.sap_infrastructure.sap_hypervisor_node_preconfigure
